const ActionTypes = {
  GET_INCOME_DATA: 'GET_INCOME_DATA',
  GET_SPENDING_DATA: 'GET_SPENDING_DATA',
  ADD_INCOME_ITEM: 'ADD_INCOME_ITEM',
  ADD_SPENDING_ITEM: 'ADD_SPENDING_ITEM',
};

export default ActionTypes;
